name: Weekly Stock ETL

on:
  schedule:
    - cron: '0 12 * * 1'  # Lunes 7am Lima (12 UTC)
  workflow_dispatch:      # Permite ejecutarlo manualmente desde GitHub

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run ETL script
      run: python main_stock_etl_clean.py

    - name: Commit updated graph
      env:
        REPO: ${{ github.repository }}
        TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add images/top10_graph.png
        git commit -m "Update weekly chart" || echo "No changes to commit"
        git push "https://x-access-token:${TOKEN}@github.com/${REPO}.git" HEAD:main

